version: '3.8'

services:
  database:
    image: postgres:14-alpine
    container_name: astro-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - astro-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astro-server
    command:
      - "${GRPC_PORT}"
      - "database"
      - "5432"
      - "${POSTGRES_DB}"
      - "${POSTGRES_USER}"
      - "${POSTGRES_PASSWORD}"
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - astro-network
    volumes:
      - ./applogs:/app/applogs

volumes:
  pgdata:

networks:
  astro-network:
    driver: bridge